python cut-silhouette.py --truth-dir /home/kennychufk/workspace/pythonWs/test-run-al-outside/truth/rltruth-1313ed22-1026.19.16.09 --shape-dir /home/kennychufk/workspace/pythonWs/shape-al
python cut-silhouette.py --truth-dir /home/kennychufk/workspace/pythonWs/test-run-al-outside/truth/rltruth-27e78d56-1026.13.28.06 --shape-dir /home/kennychufk/workspace/pythonWs/shape-al
python cut-silhouette.py --truth-dir /home/kennychufk/workspace/pythonWs/test-run-al-outside/truth/rltruth-2b6bbb7a-1028.13.46.04 --shape-dir /home/kennychufk/workspace/pythonWs/shape-al
python cut-silhouette.py --truth-dir /home/kennychufk/workspace/pythonWs/test-run-al-outside/truth/rltruth-48d51866-1026.12.46.58 --shape-dir /home/kennychufk/workspace/pythonWs/shape-al
python cut-silhouette.py --truth-dir /home/kennychufk/workspace/pythonWs/test-run-al-outside/truth/rltruth-55255d89-1026.13.08.31 --shape-dir /home/kennychufk/workspace/pythonWs/shape-al
python cut-silhouette.py --truth-dir /home/kennychufk/workspace/pythonWs/test-run-al-outside/truth/rltruth-5e06f1b4-1026.13.44.59 --shape-dir /home/kennychufk/workspace/pythonWs/shape-al
python cut-silhouette.py --truth-dir /home/kennychufk/workspace/pythonWs/test-run-al-outside/truth/rltruth-69937a1e-1027.19.15.09 --shape-dir /home/kennychufk/workspace/pythonWs/shape-al
python cut-silhouette.py --truth-dir /home/kennychufk/workspace/pythonWs/test-run-al-outside/truth/rltruth-7b7d9b3c-1026.15.05.53 --shape-dir /home/kennychufk/workspace/pythonWs/shape-al
python cut-silhouette.py --truth-dir /home/kennychufk/workspace/pythonWs/test-run-al-outside/truth/rltruth-9447355f-1026.16.57.36 --shape-dir /home/kennychufk/workspace/pythonWs/shape-al
python cut-silhouette.py --truth-dir /home/kennychufk/workspace/pythonWs/test-run-al-outside/truth/rltruth-c2276efc-1026.14.08.03 --shape-dir /home/kennychufk/workspace/pythonWs/shape-al
python cut-silhouette.py --truth-dir /home/kennychufk/workspace/pythonWs/test-run-al-outside/truth/rltruth-cff3a4f0-1026.18.33.28 --shape-dir /home/kennychufk/workspace/pythonWs/shape-al
python cut-silhouette.py --truth-dir /home/kennychufk/workspace/pythonWs/test-run-al-outside/truth/rltruth-d23ac540-1026.19.38.53 --shape-dir /home/kennychufk/workspace/pythonWs/shape-al
python cut-silhouette.py --truth-dir /home/kennychufk/workspace/pythonWs/test-run-al-outside/truth/rltruth-d4a620c3-1026.12.17.12 --shape-dir /home/kennychufk/workspace/pythonWs/shape-al
